spring.application.name=bff
cron.horario=0 0/5 * * * ?
usuario.cron=admin@cron.com
senha.cron=admincron
usuario.url=localhost:8080/usuario
tarefa.url=localhost:8081/tarefas
email.url=localhost:8082/email
server.port=8083
feign.okhttp.enabled=true